language: go

# To ensure installation of dep binary to somewhere at reasonable PATH
sudo: required

env:
 - GO15VENDOREXPERIMENT=1

# Allow use in forks
go_import_path: github.com/vektra/mockery

go:
  - 1.5.x
#  - 1.6.x
#  - 1.7.x
#  - 1.8.x
#  - 1.9.x
#  - tip

before_script:
  - sudo curl -L https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /usr/local/bin/dep
  - sudo chmod +x /usr/local/bin/dep
  - dep ensure
  - ls -alh vendor/
  - echo $GOPATH
  - go list ./...
  - GO15VENDOREXPERIMENT=1 go list ./...
