language: go

env:
 - GO15VENDOREXPERIMENT=1

# Allow use in forks
go_import_path: github.com/vektra/mockery

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

before_script:
  - curl https://glide.sh/get | sh
  - glide install
