[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  name = "golang.org/x/tools"
  branch = "release-branch.go1.5"
  source = "https://github.com/golang/tools.git"
